stages:
  - test
  - publish

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  untracked: false
  paths:
    - "sbt-cache/.ivy/cache"
    - "sbt-cache/.boot"
    - "sbt-cache/.sbtboot"
    - "sbt-cache/target"

before_script:
  - apt-get update -yqq
  - apt-get install -yqq apt-transport-https ca-certificates
  - echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - apt-get update -yqq
  - apt-get install -yqq sbt
  - sbt sbtVersion
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - git remote set-url origin git@gitlab.mdcatapult.io:$CI_PROJECT_PATH.git
  - git config --global user.email "${GIT_RELEASE_EMAIL}"
  - git config --global user.name "${GIT_RELEASE_USER}"

test:
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/
  image: openjdk:11
  script:
    - sbt clean coverage test coverageReport coverageOff

publish-snapshot:
  stage: publish
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/
  image: openjdk:11
  script:
    - sbt publish
  only:
    - develop

release-master:
  stage: publish
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/
  image: openjdk:11
  script:
    - git checkout master
    - git pull origin master
    - sbt "release with-defaults"
    - export RELEASE_TAG=$(git describe --abbrev=0)
    - >
      curl --header 'Content-Type: application/json'
      --header "PRIVATE-TOKEN: $GIT_RELEASE_TOKEN"
      --data "{ \"name\": \"$RELEASE_TAG\", \"tag_name\": \"$RELEASE_TAG\", \"description\": \"Automated CI Release of $RELEASE_TAG\" }"
      --request POST https://gitlab.mdcatapult.io/api/v4/projects/$CI_PROJECT_ID/releases
    - git checkout develop
    - git pull
    - git rebase master
    - git push origin develop
  only:
    - master