stages:
  - test
  - publish

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  untracked: false
  paths:
    - "sbt-cache/.ivy/cache"
    - "sbt-cache/.boot"
    - "sbt-cache/.sbtboot"
    - "sbt-cache/target"

before_script:
  - git remote set-url origin https://$GIT_PUSH_USER:$GIT_PUSH_TOKEN@md.catapult.org.uk/$CI_PROJECT_PATH.git
  - git config --global user.email "${GIT_RELEASE_EMAIL}"
  - git config --global user.name "${GIT_RELEASE_USER}"
  - apt-get update -yqq
  - apt-get install -yqq apt-transport-https ca-certificates
  - echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - apt-get update -yqq
  - apt-get install -yqq sbt
  - sbt sbtVersion

test:
  stage: test
  image: openjdk:11
  script:
    - sbt clean coverage test coverageReport coverageOff

publish-snapshot:
  stage: publish
  image: openjdk:11
  script:
    - sbt publish
  only:
    - develop

release-master:
  stage: publish
  image: openjdk:11
  script:
    - git checkout master
    - sbt "release with-defaults"
    - git checkout develop
    - git rebase develop
    - git push origin develop
  only:
    - master